baseURL: https://lawsssscat.github.io/hugo-usage-doc/
title: Hugo 使用手册
languageCode: zh-Hans
defaultContentLanguage: en
description: &site_description 整理使用 Hugo 时的常用资料以及使用心得
theme: [docsy]

enableRobotsTXT: true
enableGitInfo: true

menu:
  main:
    - name: "GitHub"
      weight: 50
      url: &github_repo https://github.com/LawssssCat/hugo-usage-doc
      pre: "<i class='fab fa-github'></i>"
    - name: "blog"
      weight: 30
      url: "blog"
      # pre: "<i class='fas fa-tv'></i>"
    - name: "docs"
      weight: 20
      url: "docs"
      # pre: "<i class='fas fa-tv'></i>"

taxonomies:
  tag: tags
  category: categories

params:
  copyright: "-" 
  site_description: *site_description
  github_repo: *github_repo
  # search
  offlineSearch: true
  algolia_docsearch: false

outputs:
  section:
    - HTML
    - RSS
    - print
