goldmark:
  parser:
    attribute:
      block: true
  renderer:
    unsafe: true

highlight:
  anchorLineNos: true
  codeFences: true
  guessSyntax: false
  hl_Lines: ""
  hl_inline: false
  lineAnchors: ""
  lineNoStart: 1
  lineNos: true
  lineNumbersInTable: false
  noClasses: true
  noHl: false
  # style: monokai
  tabWidth: 4

tableOfContents:
  ordered: false
  startLevel: 2
  endLevel: 4
